### PR TITLE
Add support for using runtime_cast without requiring type_id_runtime.

### PR DESCRIPTION
**Pull request by cdglove**
Add BOOST_TYPE_INDEX_IMPLEMENT_RUNTIME_CAST, which implements the functionality for runtime_cast to function, but does not include the BOOST_TYPE_INDEX_REGISTER_CLASS macro.

Reimplement BOOST_TYPE_INDEX_REGISTER_RUNTIME_CLASS to simply call BOOST_TYPE_INDEX_IMPLEMENT_RUNTIME_CAST and BOOST_TYPE_INDEX_REGISTER_CLASS.

This allows users to opt-in to one or the other, instead of forcing them to generate both virtual functions.

### CODE REVIEW

**Comment by apolukhin** [comment]
Looks good. Could you please add more tests on the new macro?

**Comment by apolukhin** [comment]
@cdglove  ping :)

**Comment by cdglove** [comment]
Sorry, been busy! Yes, I will add more tests this weekend and update the PR.

**Comment by apolukhin** [comment]
Cool feature! Thanks!

**Pull request merged**
